services:
  db:
    image: postgres:17.4-alpine3.21
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Vc617eNaA0v1j6B
      - POSTGRES_PASSWORD=RPu4Jito7ZjZWrEnDeB4dS0UxVuEIJhvMGXiXbw0Sr6uTd2Li2h7wE1YI60L6RtrsoY8h2bfjAPZ7z1nkbpeV
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo_filestore:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=Vc617eNaA0v1j6B
      - PASSWORD=RPu4Jito7ZjZWrEnDeB4dS0UxVuEIJhvMGXiXbw0Sr6uTd2Li2h7wE1YI60L6RtrsoY8h2bfjAPZ7z1nkbpeV
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_filestore:
  odoo_addons: