services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1000:1000"
      - "1001:1001"
    depends_on:
      - "database"
    networks:
      - "odoo"
    volumes:
      - "addons:/mnt/extra-addons"
      - "filestore:/var/lib/odoo"
    environment:
      - "HOST=database"
      - "USER=Vc617eNaA0v1j6B"
      - "PASSWORD=Vc617eNaA0v1j6B"

  database:
    image: postgres:17.4-alpine3.21
    restart: always
    networks:
      - "odoo"
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=Vc617eNaA0v1j6B"
      - "POSTGRES_PASSWORD=Vc617eNaA0v1j6B"

volumes:
  database:
  filestore:
  addons:

networks:
  odoo: