[options]
admin_passwd = O7eRr6ZpFezFoDsI
http_port = 1000
gevent_port = 1001
addons_path = /usr/lib/python3/dist-packages/odoo/addons, /mnt/1st_party, /mnt/2nd_party, /mnt/misc-addons, /mnt/extra-addons
data_dir = /var/lib/odoo
log_level = warn
proxy_mode = true
server_wide_modules = base, web

#odoo_parameters
workers = 2
db_maxconn = 128
limit_time_cpu = 3600
limit_time_real = 3600
limit_time_real_cron = -1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192